// Brings eigener Artikelkatalog, einmalig aus
// https://web.getbring.com/locale/catalog.de-DE.json gezogen (Stand 28.07.2026).
// Dient als Rückfallebene: bring_shopping füllt `category` nur bei selbst angelegten
// Artikeln, Standardartikel wie "Bananen" bleiben dort leer.

// Reihenfolge wie bei Bring — entspricht grob dem Weg durch den Laden.
const BRING_SEKTIONEN = [
  "Obst & Gemüse",
  "Brot & Gebäck",
  "Milch & Käse",
  "Fleisch & Fisch",
  "Zutaten & Gewürze",
  "Fertig- & Tiefkühlprodukte",
  "Getreideprodukte",
  "Snacks & Süsswaren",
  "Getränke",
  "Haushalt",
  "Pflege & Gesundheit",
  "Tierbedarf",
  "Baumarkt & Garten",
];

// 401 Suchbegriffe → Sektion, Schlüssel normalisiert (siehe bringNorm).
const BRING_ARTIKEL = {
  abfallsacke: "Haushalt",
  ahornsirup: "Zutaten & Gewürze",
  alufolie: "Haushalt",
  ananas: "Obst & Gemüse",
  apfel: "Obst & Gemüse",
  apfelmus: "Zutaten & Gewürze",
  apfelsaft: "Getränke",
  aprikosen: "Obst & Gemüse",
  artischocken: "Obst & Gemüse",
  aubergine: "Obst & Gemüse",
  aufschnitt: "Fleisch & Fisch",
  avocado: "Obst & Gemüse",
  babynahrung: "Haushalt",
  backpapier: "Haushalt",
  backpulver: "Zutaten & Gewürze",
  badreiniger: "Haushalt",
  baguette: "Brot & Gebäck",
  balsamico: "Zutaten & Gewürze",
  bananen: "Obst & Gemüse",
  basilikum: "Obst & Gemüse",
  basmatireis: "Getreideprodukte",
  batterien: "Haushalt",
  baumnusse: "Zutaten & Gewürze",
  bbqsauce: "Zutaten & Gewürze",
  beeren: "Obst & Gemüse",
  bier: "Getränke",
  binden: "Pflege & Gesundheit",
  birnen: "Obst & Gemüse",
  blatterteig: "Brot & Gebäck",
  blauschimmelkase: "Milch & Käse",
  blumen: "Haushalt",
  blumenerde: "Baumarkt & Garten",
  blumenkohl: "Obst & Gemüse",
  bodylotion: "Pflege & Gesundheit",
  bohnen: "Zutaten & Gewürze",
  bouillon: "Zutaten & Gewürze",
  bratensauce: "Zutaten & Gewürze",
  bratwurst: "Fleisch & Fisch",
  brezeln: "Snacks & Süsswaren",
  bring: "Snacks & Süsswaren",
  brokkoli: "Obst & Gemüse",
  brombeeren: "Obst & Gemüse",
  brot: "Brot & Gebäck",
  brotchen: "Brot & Gebäck",
  bruhe: "Zutaten & Gewürze",
  burrata: "Milch & Käse",
  butter: "Milch & Käse",
  champagner: "Getränke",
  champignons: "Obst & Gemüse",
  cherrytomaten: "Obst & Gemüse",
  chickenwings: "Fertig- & Tiefkühlprodukte",
  chili: "Obst & Gemüse",
  chinesetogo: "Fertig- & Tiefkühlprodukte",
  chinesischesessen: "Fertig- & Tiefkühlprodukte",
  chips: "Snacks & Süsswaren",
  cola: "Getränke",
  colalight: "Getränke",
  conditioner: "Pflege & Gesundheit",
  cornflakes: "Getreideprodukte",
  couscous: "Getreideprodukte",
  cremefraiche: "Milch & Käse",
  croissant: "Brot & Gebäck",
  datteln: "Obst & Gemüse",
  deo: "Pflege & Gesundheit",
  dessert: "Snacks & Süsswaren",
  dip: "Zutaten & Gewürze",
  dorrobst: "Snacks & Süsswaren",
  dosentomaten: "Zutaten & Gewürze",
  dunger: "Baumarkt & Garten",
  duschgel: "Pflege & Gesundheit",
  duschmittel: "Pflege & Gesundheit",
  eier: "Milch & Käse",
  eis: "Fertig- & Tiefkühlprodukte",
  eistee: "Getränke",
  energydrink: "Getränke",
  erbsen: "Obst & Gemüse",
  erdbeeren: "Obst & Gemüse",
  erdnusse: "Snacks & Süsswaren",
  essig: "Zutaten & Gewürze",
  essiggurken: "Zutaten & Gewürze",
  feigen: "Obst & Gemüse",
  fenchel: "Obst & Gemüse",
  feta: "Milch & Käse",
  feuchttucher: "Pflege & Gesundheit",
  fisch: "Fleisch & Fisch",
  fischfutter: "Tierbedarf",
  fischstabchen: "Fertig- & Tiefkühlprodukte",
  fischstabli: "Fertig- & Tiefkühlprodukte",
  fleisch: "Fleisch & Fisch",
  fondue: "Milch & Käse",
  fonduekase: "Milch & Käse",
  frankfurter: "Fleisch & Fisch",
  frischhaltefolie: "Haushalt",
  frischkase: "Milch & Käse",
  fruchte: "Obst & Gemüse",
  fruchtsaft: "Getränke",
  fruhlingszwiebeln: "Obst & Gemüse",
  garnelen: "Fleisch & Fisch",
  gartenwerkzeug: "Baumarkt & Garten",
  gelee: "Snacks & Süsswaren",
  gemuse: "Obst & Gemüse",
  gemusegefroren: "Fertig- & Tiefkühlprodukte",
  geschenk: "Haushalt",
  geschenkpapier: "Haushalt",
  geschirrglanz: "Haushalt",
  geschirrsalz: "Haushalt",
  geschirrtabs: "Haushalt",
  gesichtscreme: "Pflege & Gesundheit",
  getranke: "Getränke",
  getreideriegel: "Snacks & Süsswaren",
  getrocknetetomaten: "Obst & Gemüse",
  giesskanne: "Baumarkt & Garten",
  gin: "Getränke",
  gipfeli: "Brot & Gebäck",
  glace: "Fertig- & Tiefkühlprodukte",
  glasreiniger: "Haushalt",
  gluhbirne: "Haushalt",
  gnocchi: "Getreideprodukte",
  gorgonzola: "Milch & Käse",
  grapefruit: "Obst & Gemüse",
  griess: "Getreideprodukte",
  grill: "Baumarkt & Garten",
  grunebohnen: "Obst & Gemüse",
  guetzli: "Snacks & Süsswaren",
  gurke: "Obst & Gemüse",
  haargel: "Pflege & Gesundheit",
  haarspray: "Pflege & Gesundheit",
  haarspulung: "Pflege & Gesundheit",
  hackfleisch: "Fleisch & Fisch",
  haferflocken: "Getreideprodukte",
  hahnchen: "Fleisch & Fisch",
  hahnchenbrust: "Fleisch & Fisch",
  handcreme: "Pflege & Gesundheit",
  haselnusse: "Zutaten & Gewürze",
  haushaltspapier: "Haushalt",
  hefe: "Zutaten & Gewürze",
  heidelbeeren: "Obst & Gemüse",
  himbeeren: "Obst & Gemüse",
  holzkohle: "Baumarkt & Garten",
  honig: "Snacks & Süsswaren",
  hundefutter: "Tierbedarf",
  hundesnack: "Tierbedarf",
  huttenkase: "Milch & Käse",
  indiantogo: "Fertig- & Tiefkühlprodukte",
  indischesessen: "Fertig- & Tiefkühlprodukte",
  ingwer: "Obst & Gemüse",
  insektenschutzmittel: "Pflege & Gesundheit",
  italiantogo: "Fertig- & Tiefkühlprodukte",
  italienischesessen: "Fertig- & Tiefkühlprodukte",
  joghurt: "Milch & Käse",
  kaffee: "Zutaten & Gewürze",
  kaffeebohnen: "Zutaten & Gewürze",
  kaffeekapseln: "Zutaten & Gewürze",
  kaffeepads: "Zutaten & Gewürze",
  kakao: "Getränke",
  kaki: "Obst & Gemüse",
  kalbfleisch: "Fleisch & Fisch",
  karotten: "Obst & Gemüse",
  kartoffeln: "Obst & Gemüse",
  kartoffelpuree: "Zutaten & Gewürze",
  kartoffelstock: "Zutaten & Gewürze",
  kase: "Milch & Käse",
  kassler: "Fleisch & Fisch",
  katzenfutter: "Tierbedarf",
  katzensnack: "Tierbedarf",
  katzenstreu: "Tierbedarf",
  kaugummi: "Snacks & Süsswaren",
  kekse: "Snacks & Süsswaren",
  kerzen: "Haushalt",
  ketchup: "Zutaten & Gewürze",
  kichererbsen: "Getreideprodukte",
  kirschen: "Obst & Gemüse",
  kiwi: "Obst & Gemüse",
  klarspuler: "Haushalt",
  knackebrot: "Brot & Gebäck",
  knoblauch: "Obst & Gemüse",
  knodel: "Fertig- & Tiefkühlprodukte",
  kohl: "Obst & Gemüse",
  kohlrabi: "Obst & Gemüse",
  kokosmilch: "Zutaten & Gewürze",
  kondome: "Pflege & Gesundheit",
  konfiture: "Snacks & Süsswaren",
  koriander: "Obst & Gemüse",
  kosmetiktucher: "Pflege & Gesundheit",
  krauter: "Obst & Gemüse",
  krauterbutter: "Milch & Käse",
  kuchen: "Snacks & Süsswaren",
  kuchenrolle: "Haushalt",
  kurbis: "Obst & Gemüse",
  lachs: "Fleisch & Fisch",
  lamm: "Fleisch & Fisch",
  lasagne: "Fertig- & Tiefkühlprodukte",
  lattich: "Obst & Gemüse",
  lauch: "Obst & Gemüse",
  lebkuchen: "Snacks & Süsswaren",
  lightlimonade: "Getränke",
  limette: "Obst & Gemüse",
  limonade: "Getränke",
  linsen: "Zutaten & Gewürze",
  linsenmittel: "Pflege & Gesundheit",
  lippenpflege: "Pflege & Gesundheit",
  lippenpomade: "Pflege & Gesundheit",
  mais: "Obst & Gemüse",
  makeupentferner: "Pflege & Gesundheit",
  mandarinen: "Obst & Gemüse",
  mandelmus: "Zutaten & Gewürze",
  mandeln: "Zutaten & Gewürze",
  mango: "Obst & Gemüse",
  margarine: "Milch & Käse",
  marmelade: "Snacks & Süsswaren",
  marzipan: "Zutaten & Gewürze",
  mascarpone: "Milch & Käse",
  mayonnaise: "Zutaten & Gewürze",
  mehl: "Getreideprodukte",
  melone: "Obst & Gemüse",
  mettfurigel: "Fleisch & Fisch",
  mettigel: "Fleisch & Fisch",
  milch: "Milch & Käse",
  mineralwasser: "Getränke",
  mozzarella: "Milch & Käse",
  muesli: "Getreideprodukte",
  muffins: "Brot & Gebäck",
  mullsacke: "Haushalt",
  mundspulung: "Pflege & Gesundheit",
  muscheln: "Fleisch & Fisch",
  musli: "Getreideprodukte",
  nagel: "Baumarkt & Garten",
  nagellack: "Pflege & Gesundheit",
  nagellackentferner: "Pflege & Gesundheit",
  nektarine: "Obst & Gemüse",
  nougatcreme: "Snacks & Süsswaren",
  nudeln: "Getreideprodukte",
  nusse: "Zutaten & Gewürze",
  obst: "Obst & Gemüse",
  ol: "Zutaten & Gewürze",
  oliven: "Obst & Gemüse",
  olivenol: "Zutaten & Gewürze",
  orange: "Obst & Gemüse",
  orangensaft: "Getränke",
  oregano: "Zutaten & Gewürze",
  paniermehl: "Zutaten & Gewürze",
  paprika: "Obst & Gemüse",
  paprikapulver: "Zutaten & Gewürze",
  parmesan: "Milch & Käse",
  passionsfrucht: "Obst & Gemüse",
  pastasauce: "Zutaten & Gewürze",
  pelati: "Zutaten & Gewürze",
  penne: "Getreideprodukte",
  peperoncini: "Obst & Gemüse",
  peperoni: "Obst & Gemüse",
  petersilie: "Obst & Gemüse",
  pfeffer: "Zutaten & Gewürze",
  pfefferkorner: "Zutaten & Gewürze",
  pfefferminze: "Obst & Gemüse",
  pfirsich: "Obst & Gemüse",
  pflanzen: "Baumarkt & Garten",
  pflaster: "Pflege & Gesundheit",
  pflaumen: "Obst & Gemüse",
  pilze: "Obst & Gemüse",
  pinienkerne: "Zutaten & Gewürze",
  pinsel: "Baumarkt & Garten",
  pizza: "Fertig- & Tiefkühlprodukte",
  pizzateig: "Brot & Gebäck",
  platzchen: "Snacks & Süsswaren",
  pommeschips: "Snacks & Süsswaren",
  pommesfrites: "Fertig- & Tiefkühlprodukte",
  popcorn: "Snacks & Süsswaren",
  poulet: "Fleisch & Fisch",
  pouletbrustli: "Fleisch & Fisch",
  preiselbeersauce: "Zutaten & Gewürze",
  propangas: "Baumarkt & Garten",
  prosecco: "Getränke",
  puderzucker: "Zutaten & Gewürze",
  putzmittel: "Haushalt",
  quark: "Milch & Käse",
  raclette: "Milch & Käse",
  raclettekase: "Milch & Käse",
  radieschen: "Obst & Gemüse",
  rahm: "Milch & Käse",
  rasenmaher: "Baumarkt & Garten",
  rasierer: "Pflege & Gesundheit",
  rasierklingen: "Pflege & Gesundheit",
  rasierschaum: "Pflege & Gesundheit",
  reibkase: "Milch & Käse",
  reis: "Getreideprodukte",
  rhabarber: "Obst & Gemüse",
  ricotta: "Milch & Käse",
  rindergeschnetzeltes: "Fleisch & Fisch",
  rindfleisch: "Fleisch & Fisch",
  rindsgeschnetzeltes: "Fleisch & Fisch",
  risottoreis: "Getreideprodukte",
  rohschinken: "Fleisch & Fisch",
  rosmarin: "Zutaten & Gewürze",
  rotebete: "Obst & Gemüse",
  rotwein: "Getränke",
  rucola: "Obst & Gemüse",
  rum: "Getränke",
  sahne: "Milch & Käse",
  salami: "Fleisch & Fisch",
  salat: "Obst & Gemüse",
  salatsauce: "Zutaten & Gewürze",
  salbei: "Obst & Gemüse",
  salz: "Zutaten & Gewürze",
  salzstangen: "Snacks & Süsswaren",
  samen: "Baumarkt & Garten",
  samereien: "Baumarkt & Garten",
  sardellen: "Fleisch & Fisch",
  sauerkraut: "Zutaten & Gewürze",
  sauerrahm: "Milch & Käse",
  schinken: "Fleisch & Fisch",
  schmand: "Milch & Käse",
  schmerzmittel: "Pflege & Gesundheit",
  schnaps: "Getränke",
  schnittlauch: "Obst & Gemüse",
  schnitzel: "Fleisch & Fisch",
  schokolade: "Snacks & Süsswaren",
  schrauben: "Baumarkt & Garten",
  schwamm: "Haushalt",
  schweinefleisch: "Fleisch & Fisch",
  seife: "Pflege & Gesundheit",
  sekt: "Getränke",
  sellerie: "Obst & Gemüse",
  semmelbrosel: "Zutaten & Gewürze",
  senf: "Zutaten & Gewürze",
  servietten: "Haushalt",
  shampoo: "Pflege & Gesundheit",
  silberzwiebeln: "Zutaten & Gewürze",
  sirup: "Getränke",
  smoothie: "Getränke",
  snacks: "Snacks & Süsswaren",
  sojamilch: "Milch & Käse",
  sojasauce: "Zutaten & Gewürze",
  sonnencreme: "Pflege & Gesundheit",
  sonnenschirm: "Baumarkt & Garten",
  soyamilch: "Milch & Käse",
  soyasauce: "Zutaten & Gewürze",
  spaghetti: "Getreideprodukte",
  spargel: "Obst & Gemüse",
  speck: "Fleisch & Fisch",
  speisestarke: "Zutaten & Gewürze",
  spinat: "Obst & Gemüse",
  sportgetrank: "Getränke",
  spulmittel: "Haushalt",
  steak: "Fleisch & Fisch",
  streichholzer: "Haushalt",
  strohhalme: "Haushalt",
  suppe: "Fertig- & Tiefkühlprodukte",
  sussigkeiten: "Snacks & Süsswaren",
  susskartoffeln: "Obst & Gemüse",
  tampons: "Pflege & Gesundheit",
  taschentucher: "Pflege & Gesundheit",
  tee: "Getränke",
  thaiessen: "Fertig- & Tiefkühlprodukte",
  thaitogo: "Fertig- & Tiefkühlprodukte",
  thunfisch: "Fleisch & Fisch",
  thymian: "Obst & Gemüse",
  toast: "Brot & Gebäck",
  tofu: "Getreideprodukte",
  toilettenpapier: "Pflege & Gesundheit",
  toilettenreiniger: "Haushalt",
  tomaten: "Obst & Gemüse",
  tomatenmark: "Zutaten & Gewürze",
  tomatensauce: "Zutaten & Gewürze",
  tonicwater: "Getränke",
  topfe: "Baumarkt & Garten",
  torte: "Snacks & Süsswaren",
  tortillachips: "Snacks & Süsswaren",
  trauben: "Obst & Gemüse",
  vanillesauce: "Snacks & Süsswaren",
  vanillezucker: "Zutaten & Gewürze",
  vielendank: "Snacks & Süsswaren",
  vitamine: "Pflege & Gesundheit",
  vodka: "Getränke",
  vogelfutter: "Tierbedarf",
  waffeln: "Brot & Gebäck",
  walnusse: "Zutaten & Gewürze",
  waschmittel: "Haushalt",
  wasser: "Getränke",
  wassermelone: "Obst & Gemüse",
  wattepads: "Pflege & Gesundheit",
  watterondellen: "Pflege & Gesundheit",
  wattestabchen: "Pflege & Gesundheit",
  wcpapier: "Pflege & Gesundheit",
  wcreiniger: "Haushalt",
  weichspuler: "Haushalt",
  weisswein: "Getränke",
  whisky: "Getränke",
  windeln: "Pflege & Gesundheit",
  wodka: "Getränke",
  wurst: "Fleisch & Fisch",
  zahnbursten: "Pflege & Gesundheit",
  zahnpasta: "Pflege & Gesundheit",
  zahnseide: "Pflege & Gesundheit",
  zahnstocher: "Haushalt",
  zigaretten: "Getränke",
  zimt: "Zutaten & Gewürze",
  zitrone: "Obst & Gemüse",
  zucchetti: "Obst & Gemüse",
  zucchini: "Obst & Gemüse",
  zucker: "Zutaten & Gewürze",
  zwiebeln: "Obst & Gemüse",
};

function bringNorm(text) {
  return text
    .toLowerCase()
    .replace(/ä/g, "a").replace(/ö/g, "o").replace(/ü/g, "u").replace(/ß/g, "ss")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "");
}

// Katalogbegriffe lang zuerst, damit "Buttermilch" nicht vorschnell an "Milch" hängen bleibt.
const BRING_SCHLUESSEL = Object.keys(BRING_ARTIKEL).sort((a, b) => b.length - a.length);

// Sektion zu einem Artikelnamen raten. Reihenfolge: eigene Ausnahme, exakter Treffer,
// Wortstamm, einzelnes Wort. Gibt null zurück, wenn nichts passt - der Artikel landet
// dann sichtbar unter "Ohne Kategorie", und das ist die Einladung, ihn in
// CONFIG.shopping.kategorien einzutragen.
function bringKategorie(name, ausnahmen) {
  const n = bringNorm(name);
  if (ausnahmen) {
    for (const [begriff, sektion] of Object.entries(ausnahmen)) {
      if (bringNorm(begriff) === n) return sektion;
    }
  }
  if (BRING_ARTIKEL[n]) return BRING_ARTIKEL[n];
  for (const k of BRING_SCHLUESSEL) {
    if (k.length >= 4 && n.includes(k)) return BRING_ARTIKEL[k];
  }
  for (const wort of name.split(/\s+/)) {
    const nw = bringNorm(wort);
    if (nw.length >= 4 && BRING_ARTIKEL[nw]) return BRING_ARTIKEL[nw];
  }
  return null;
}

// bring_shopping baut die Bild-URL aus dem Rohnamen, deshalb kommt "käse.png" statt
// "kaese.png" heraus und laeuft ins Leere. Wir bauen den Slug selbst nach Brings Regel.
function bringBildUrl(url) {
  if (!url) return null;
  const datei = url.split("/").pop().replace(/\.png$/i, "");
  const slug = datei
    .toLowerCase()
    .replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss")
    .replace(/[èéêë]/g, "e").replace(/[àâ]/g, "a").replace(/[îï]/g, "i").replace(/ç/g, "c")
    .replace(/[^a-z0-9]/g, "");
  return slug ? `https://web.getbring.com/assets/images/items/${slug}.png` : null;
}
